### PR TITLE
Optionally respond with CORS headers

### PR DESCRIPTION
**Pull request by doublesharp**
I am developing an application that runs on dynamic hostnames and needed to respond with CORS headers for static content. The new method adds headers to the response that allow the content to be loaded in the browser.

### CODE REVIEW

**Comment by ericmdantas** [comment]
Good job, thanks for the PR.

Only two things before I merge: could you also add a test in `options_test.js`? Also, could you document the new option in the Readme?

Once that's done, I'll merge and release `1.4.3`. Thanks!

**Comment by ericmdantas** [comment]
Thanks! Merged.

**Comment by doublesharp** [comment]
Awesome, thanks. Aliv has been very useful in our development environment :)

**Comment by doublesharp** [comment]
I was just about to switch back to the npm version and saw that you haven't published 1.5 - are you planning additional changes?

**Comment by ericmdantas** [comment]
Nope, having problems with the publish.

```events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\bin\_mocha:425:12
    at Array.forEach (native)
    at exit (C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\bin\_mocha:422:11)
    at done (C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\lib\mocha.js:497:13)
    at Runner.<anonymous> (C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\lib\runner.js:804:5)
    at emitNone (events.js:91:20)
    at Runner.emit (events.js:185:7)
    at C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\lib\runner.js:791:12
    at C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\lib\runner.js:644:9
    at next (C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\lib\runner.js:284:14)
    at Immediate.<anonymous> (C:\Users\_eric\Documents\projects\aliv\node_modules\mocha\lib\runner.js:320:5)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
npm ERR! Test failed.  See above for more details.
```

**Comment by doublesharp** [comment]
Good times... It looks like you are on Windows, so perhaps it is this issue https://github.com/nodejs/node/issues/9542? What version of Node are you using? If it is that issue, it looks like the fix is to upgrade to a newer version of Node.

**Comment by ericmdantas** [comment]
Yeah, that was the issue. I had Node `7.1.0` here, updating to `7.4.0` did the trick. 

Thanks once again, now it's published on npm!

**Pull request merged**
